import requests
from influxdb import InfluxDBClient
from datetime import datetime

# =====================================================
# InfluxDB Configuration
# =====================================================

INFLUX_HOST = "localhost"
INFLUX_PORT = 8086
INFLUX_DB = "jmeter"

client = InfluxDBClient(
    host=INFLUX_HOST,
    port=INFLUX_PORT
)

client.switch_database(INFLUX_DB)

# =====================================================
# Services
# =====================================================

SERVICES = {
    "gateway": "http://localhost:8090",
    "user-service": "http://localhost:8081",
    "product-service": "http://localhost:8082",
    "order-service": "http://localhost:8083"
}

# =====================================================
# Run Information
# =====================================================

#RUN_ID = "RUN_" + datetime.now().strftime("%Y%m%d_%H%M%S")
# Read run_id generated by execution_history_writer.py

with open("current_run_id.txt", "r") as f:
    RUN_ID = f.read().strip()

print(f"Using Run ID: {RUN_ID}")

# =====================================================
# Helper Methods
# =====================================================

def get_metric(base_url, metric_name):

    url = f"{base_url}/actuator/metrics/{metric_name}"

    try:
        response = requests.get(url, timeout=10)

        if response.status_code != 200:
            return None

        payload = response.json()

        measurements = payload.get("measurements", [])

        if not measurements:
            return None

        return measurements[0]["value"]

    except Exception as ex:
        print(f"ERROR [{metric_name}] : {ex}")
        return None


# =====================================================
# Collect Metrics
# =====================================================

json_body = []

for service_name, service_url in SERVICES.items():

    print(f"\nCollecting metrics from {service_name}")

    cpu_usage_raw = get_metric(
    service_url,
    "system.cpu.usage"
)

    cpu_usage = round((cpu_usage_raw or 0) * 100, 2)

    memory_bytes = get_metric(
        service_url,
        "jvm.memory.used"
    )

    thread_count = get_metric(
        service_url,
        "jvm.threads.live"
    )

    if memory_bytes:
        memory_mb = round(memory_bytes / 1024 / 1024, 2)
    else:
        memory_mb = None

    print(f"CPU      : {cpu_usage}")
    print(f"MemoryMB : {memory_mb}")
    print(f"Threads  : {thread_count}")

    point = {
        "measurement": "aiperf_service_metrics",
        "tags": {
            "run_id": RUN_ID,
            "service_name": service_name
        },
        "fields": {
            "cpu_usage": float(cpu_usage or 0),
            "memory_used_mb": float(memory_mb or 0),
            "thread_count": int(thread_count or 0)
        }
    }

    json_body.append(point)

# =====================================================
# Write to InfluxDB
# =====================================================

if json_body:

    client.write_points(json_body)

    print("\n=================================")
    print("Metrics Successfully Written")
    print("Run ID :", RUN_ID)
    print("=================================")

else:

    print("No metrics collected")